In [1]:
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv("/kaggle/input/home-data-for-ml-course/train.csv")
test_df = pd.read_csv("/kaggle/input/home-data-for-ml-course/test.csv")

In [3]:
pd.set_option('display.max_rows', None)

In [4]:
train_df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [5]:
test_df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       227
LotArea             0
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType        894
MasVnrArea         15
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           44
BsmtCond           45
BsmtExposure       44
BsmtFinType1       42
BsmtFinSF1          1
BsmtFinType2       42
BsmtFinSF2          1
BsmtUnfSF           1
TotalBsmtSF         1
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        2
BsmtHalfBath        2
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         1
TotRmsAbvGrd        0
Functional          2
Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond         78
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1456
Fence            1169
MiscFeature      1408
MiscVal             0
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0
dtype: int64

In [6]:
train_df.set_index('Id')
test_df.set_index('Id')

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

      MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id
1461          20       RH         80.0    11622   Pave   NaN      Reg
1462          20       RL         81.0    14267   Pave   NaN      IR1
1463          60       RL         74.0    13830   Pave   NaN      IR1
1464          60       RL         78.0     9978   Pave   NaN      IR1
1465         120       RL         43.0     5005   Pave   NaN      IR1
1466          60       RL         75.0    10000   Pave   NaN      IR1
1467          20       RL          NaN     7980   Pave   NaN      IR1
1468          60       RL         63.0     8402   Pave   NaN      IR1
1469          20       RL         85.0    10176   Pave   NaN      Reg
1470          20       RL         70.0     8400   Pave   NaN      Reg
1471         120       RH         26.0     5858   Pave   NaN      IR1
1472         160       RM         21.0     1680   Pave   NaN      Reg
1473         160       RM         21.0     1680   Pave   NaN      Reg
1474         160       RL         24.0     2280   Pave   NaN      Reg
1475         120       RL         24.0     2280   Pave   NaN      Reg
1476          60       RL        102.0    12858   Pave   NaN      IR1
1477          20       RL         94.0    12883   Pave   NaN      IR1
1478          20       RL         90.0    11520   Pave   NaN      Reg
1479          20       RL         79.0    14122   Pave   NaN      IR1
1480          20       RL        110.0    14300   Pave   NaN      Reg
1481          60       RL        105.0    13650   Pave   NaN      Reg
1482         120       RL         41.0     7132   Pave   NaN      IR1
1483          20       RL        100.0    18494   Pave   NaN      IR1
1484         120       RL         43.0     3203   Pave   NaN      Reg
1485          80       RL         67.0    13300   Pave   NaN      IR1
1486          60       RL         63.0     8577   Pave   NaN      IR1
1487          60       RL         60.0    17433   Pave   NaN      IR2
1488          20       RL         73.0     8987   Pave   NaN      Reg
1489          20       FV         92.0     9215   Pave   NaN      Reg
1490          20       FV         84.0    10440   Pave   NaN      Reg
1491          60       RL         70.0    11920   Pave   NaN      Reg
1492          30       RH         70.0     9800   Pave   NaN      Reg
1493          20       RL         39.0    15410   Pave   NaN      IR1
1494          60       RL         85.0    13143   Pave   NaN      IR1
1495          60       RL         88.0    11134   Pave   NaN      Reg
1496         120       FV         25.0     4835   Pave   NaN      IR1
1497         160       FV         39.0     3515   Pave  Pave      Reg
1498         160       FV         30.0     3215   Pave  Pave      Reg
1499         160       FV         24.0     2544   Pave  Pave      Reg
1500         160       FV         24.0     2544   Pave  Pave      Reg
1501         160       FV          NaN     2980   Pave   NaN      Reg
1502         160       FV          NaN     2403   Pave   NaN      IR1
1503          20       FV         57.0    12853   Pave  Pave      IR1
1504          60       FV         68.0     7379   Pave   NaN      IR1
1505          20       FV         80.0     8000   Pave   NaN      Reg
1506          20       RL          NaN    10456   Pave   NaN      IR1
1507          60       RL         80.0    10791   Pave   NaN      Reg
1508          50       RL          NaN    18837   Pave   NaN      IR1
1509          60       RL         80.0     9600   Pave   NaN      Reg
1510          20       RL         80.0     9600   Pave   NaN      Reg
1511          20       RL         90.0     9900   Pave   NaN      Reg
1512          20       RL         88.0     9680   Pave   NaN      Reg
1513          80       RL          NaN    10600   Pave  Pave      IR1
1514          90       RL         98.0    13260   Pave   NaN      IR1
1515          50       RL         68.0     9724   Pave   NaN      Reg
1516          50       RL        120.0    17360   Pave   NaN      Reg
1517          85       RL         75.0    11380   Pave   NaN      IR1
1518          90       RL         70.0     8267   Pave   NaN      Reg
1519          20       RL         70.0     8197   Pave   NaN      Reg
1520          20       RL          NaN     8050   Pave   NaN      IR1
1521          20       RL         87.0    10725   Pave   NaN      IR1
1522          20       RL         80.0    10032   Pave   NaN      Reg
1523          50       RL         60.0     8382   Pave   NaN      Reg
1524          20       RL         60.0    10950   Pave   NaN      Reg
1525          20       RL        119.0    10895   Pave   NaN      Reg
1526         190       RL         70.0    13587   Pave   NaN      Reg
1527          30       RL         65.0     7898   Pave   NaN      Reg
1528          50       RL         60.0     8064   Pave   NaN      Reg
1529          20       RL         81.0     7635   Pave   NaN      IR1
1530          20       RL         80.0     9760   Pave   NaN      Reg
1531          50       RM         60.0     4800   Pave   NaN      Reg
1532          30       RM         56.0     4485   Pave  Grvl      Reg
1533          20       RM         69.0     5805   Pave  Grvl      Reg
1534          45       RM         50.0     6900   Pave   NaN      Reg
1535          50       RM         69.0    11851   Pave   NaN      Reg
1536          50       RM          NaN     8239   Pave   NaN      Reg
1537          30       RM         68.0     9656   Pave   NaN      Reg
1538          70       RM         60.0     9600   Pave  Grvl      Reg
1539          70       RM         50.0     9000   Pave  Grvl      Reg
1540         190       RM        100.0     9045   Pave   NaN      Reg
1541          70       RM         60.0    10560   Pave   NaN      Reg
1542          50       RM         53.0     5830   Pave   NaN      Reg
1543          75       RL          NaN     7793   Pave   NaN      IR1
1544          30       RM         50.0     5000   Pave   NaN      Reg
1545          50       RM         50.0     6000   Pave   NaN      Reg
1546          50       RM         50.0     6000   Pave   NaN      Reg
1547          50       RM         53.0     6360   Pave   NaN      Reg
1548          50       RM         50.0     6000   Pave   NaN      Reg
1549          50       RM         52.0     6240   Pave   NaN      Reg
1550          50       RM         52.0     6240   Pave   NaN      Reg
1551          30       RM         51.0     6120   Pave   NaN      Reg
1552          50       RM         57.0     8094   Pave  Grvl      Reg
1553          70       RM         60.0    12900   Pave  Grvl      Reg
1554          70       RM         52.0     3068   Pave  Grvl      Reg
1555          20       RL        100.0    15263   Pave   NaN      IR1
1556          50       RL         72.0    10632   Pave   NaN      IR1
1557         190       RL         60.0     9900   Pave   NaN      Reg
1558          50       RL         65.0     6001   Pave   NaN      IR1
1559          70  C (all)          NaN     6449   Pave   NaN      IR1
1560         190       RH         60.0     6048   Pave   NaN      Reg
1561          90       RL         72.0    10773   Pave   NaN      Reg
1562          20       RL         65.0     7800   Pave   NaN      Reg
1563          20       RL         65.0     7832   Pave   NaN      Reg
1564          90       RL          NaN     7424   Pave   NaN      IR1
1565          60       RL         86.0    11227   Pave   NaN      Reg
1566          20       RL          NaN    20062   Pave   NaN      IR1
1567          30       RL         94.0     9259   Pave   NaN      Reg
1568          60       RL          NaN    17082   Pave   NaN      IR1
1569          50       RL        124.0    18600   Pave   NaN      Reg
1570          20       RL         65.0    11479   Pave   NaN      Reg
1571          50       RL         50.0     9350   Pave   NaN      Reg
1572          20       RL         75.0     9525   Pave   NaN      Reg
1573          20       RL         44.0    17485   Pave   NaN      IR2
1574          20       RL          NaN    11200   Pave   NaN      IR1
1575          20       RL         83.0    11980   Pave   NaN      Reg
1576          60       RL         87.0    12361   Pave   NaN      IR1
1577          20       RL         64.0     7360   Pave   NaN      Reg
1578          50       RL         82.0    14235   Pave   NaN      IR1
1579          85       RL         82.0    11105   Pave   NaN      Reg
1580          60       RL          NaN     9337   Pave   NaN      IR1
1581          20       RL         38.0    15240   Pave   NaN      IR1
1582          20       RL         68.0     7480   Pave   NaN      Reg
1583          20       RL         80.0    10389   Pave   NaN      Reg
1584          60       RL         75.0     9375   Pave   NaN      Reg
1585         120       RM          NaN     4435   Pave   NaN      Reg
1586          30       RL         67.0     8777   Pave   NaN      Reg
1587          20       RL         68.0     8842   Pave   NaN      Reg
1588          20       RL         60.0    10044   Pave   NaN      IR1
1589          50       RL         89.0    11792   Pave   NaN      Reg
1590          80       RL         65.0     6305   Pave   NaN      Reg
1591          20       RL         64.0     6410   Pave   NaN      Reg
1592          30       RL         67.0     4853   Pave   NaN      Reg
1593          30       RL          NaN     7890   Pave   NaN      Reg
1594          90       RH         60.0     7200   Pave  Pave      Reg
1595          50       RL         51.0     9839   Pave   NaN      Reg
1596          50       RL         78.0    10452   Pave   NaN      IR1
1597          90       RL         78.0    15600   Pave   NaN      Reg
1598          80       RL         85.0    19645   Pave   NaN      IR1
1599         120       RM         35.0     3907   Pave   NaN      IR1
1600         120       RM         35.0     3907   Pave   NaN      IR1
1601          30       RM         58.0     8154   Pave   NaN      Reg
1602          50       RM         50.0     9140   Pave   NaN      Reg
1603          30  C (all)         66.0     8712   Grvl   NaN      Reg
1604         120       RM         44.0     3811   Pave   NaN      IR1
1605          60       RL         85.0    11050   Pave   NaN      Reg
1606          80       RL         74.0     9620   Pave   NaN      Reg
1607          90       RL          NaN    12760   Pave   NaN      IR1
1608          20       RL         88.0    11896   Pave   NaN      IR1
1609          20       RL         73.0     9803   Pave   NaN      Reg
1610          60       RL         73.0     9802   Pave   NaN      Reg
1611          20       RL         85.0    15300   Pave   NaN      Reg
1612          20       RL         93.0    10114   Pave   NaN      Reg
1613          20       RL          NaN    11875   Pave   NaN      Reg
1614         120       RM         31.0     2394   Pave   NaN      Reg
1615         160       RM         21.0     1476   Pave   NaN      Reg
1616         160       RM         21.0     1900   Pave   NaN      Reg
1617         160       RM         21.0     1890   Pave   NaN      Reg
1618          20       RL         50.0     6953   Pave   NaN      Reg
1619          20       RL         76.0    12887   Pave   NaN      Reg
1620          90       RL         70.0     7700   Pave   NaN      Reg
1621          60       RL         63.0    10475   Pave   NaN      Reg
1622          50       RL         68.0    10544   Pave   NaN      IR1
1623          20       RL         76.0     9892   Pave   NaN      Reg
1624          60       RL         74.0    12961   Pave   NaN      Reg
1625          20       RL         74.0    13008   Pave   NaN      IR1
1626          20       RL         85.0    10200   Pave   NaN      Reg
1627          60       RL         88.0    10179   Pave   NaN      IR1
1628          60       RL          NaN    11792   Pave   NaN      IR1
1629          80       RL         60.0     8400   Pave   NaN      Reg
1630         120       RL         28.0     7296   Pave   NaN      IR1
1631         120       RL         61.0     7380   Pave   NaN      IR1
1632         120       RL         57.0     8013   Pave   NaN      IR1
1633          80       RL         57.0     8923   Pave   NaN      IR1
1634          60       RL         60.0     7500   Pave   NaN      Reg
1635          60       RL          NaN     8803   Pave   NaN      IR1
1636          20       RL         58.0     7250   Pave   NaN      Reg
1637          60       RL         85.0    11900   Pave   NaN      Reg
1638          60       RL          NaN    13250   Pave   NaN      IR1
1639          20       RL         80.0    10928   Pave   NaN      Reg
1640          60       RL          NaN    12388   Pave   NaN      IR1
1641          20       RL         80.0    11088   Pave   NaN      Reg
1642          60       FV         70.0     7000   Pave   NaN      Reg
1643          60       FV          NaN     7500   Pave   NaN      Reg
1644          60       FV          NaN     8470   Pave   NaN      Reg
1645          20       RL          NaN     9373   Pave   NaN      IR1
1646          20       RL         78.0    10140   Pave   NaN      Reg
1647          20       RL         85.0    11050   Pave   NaN      IR1
1648          20       RL          NaN     7830   Pave   NaN      IR1
1649          20       RL          NaN     8510   Pave   NaN      IR1
1650          20       RL         60.0     7038   Pave   NaN      Reg
1651          20       RL         60.0     9000   Pave   NaN      Reg
1652         160       RM         21.0     1680   Pave   NaN      Reg
1653         160       RM         21.0     1680   Pave   NaN      Reg
1654         160       RL         24.0     2308   Pave   NaN      Reg
1655         120       RL         24.0     2280   Pave   NaN      Reg
1656         160       RL         24.0     2349   Pave   NaN      Reg
1657         160       RL         24.0     2364   Pave   NaN      Reg
1658         160       RL         24.0     2364   Pave   NaN      Reg
1659         120       RL         24.0     2104   Pave   NaN      Reg
1660          20       RL          NaN    10710   Pave   NaN      Reg
1661          60       RL        110.0    14257   Pave   NaN      Reg
1662          60       RL         95.0    12350   Pave   NaN      Reg
1663          20       RL         95.0    12350   Pave   NaN      Reg
1664          20       RL        105.0    13693   Pave   NaN      Reg
1665          20       RL         95.0    11578   Pave   NaN      Reg
1666          20       RL        129.0    16870   Pave   NaN      IR1
1667          60       RL         59.0    23303   Pave   NaN      IR3
1668          20       RL         87.0    10367   Pave   NaN      IR1
1669          20       RL         77.0    10872   Pave   NaN      IR1
1670          20       RL        102.0    13514   Pave   NaN      IR1
1671          20       RL         90.0    12878   Pave   NaN      IR1
1672          20       RL        110.0    15274   Pave   NaN      IR1
1673          60       RL         96.0    13262   Pave   NaN      IR1
1674          20       RL         70.0     9658   Pave   NaN      IR1
1675         120       RL         47.0     6904   Pave   NaN      IR1
1676         120       RL         34.0     5122   Pave   NaN      IR1
1677         120       RL         80.0    10307   Pave   NaN      IR1
1678          20       RL        100.0    14836   Pave   NaN      IR1
1679          20       RL        117.0    15262   Pave   NaN      IR1
1680         120       RL         44.0     7390   Pave   NaN      IR1
1681         120       RL         48.0     6472   Pave   NaN      Reg
1682          20       RL        129.0    16770   Pave   NaN      Reg
1683         120       RL         48.0     3480   Pave   NaN      Reg
1684          60       RL         63.0    10928   Pave   NaN      Reg
1685          60       RL         57.0     8918   Pave   NaN      IR1
1686         120       RL         43.0     3182   Pave   NaN      Reg
1687          80       RL         59.0     9434   Pave   NaN      IR1
1688          60       RL         62.0     7984   Pave   NaN      IR1
1689          60       RL         61.0    10125   Pave   NaN      IR1
1690          60       RL          NaN     8965   Pave   NaN      IR1
1691          60       RL          NaN     8174   Pave   NaN      IR1
1692          60       RL          NaN    12891   Pave   NaN      IR1
1693          80       RL         61.0     9734   Pave   NaN      IR1
1694          60       RL         42.0     8433   Pave   NaN      IR1
1695          80       RL         62.0     7750   Pave   NaN      Reg
1696          60       RL          NaN    15896   Pave   NaN      IR2
1697          80       RL         64.0     7848   Pave   NaN      IR1
1698          60       RL        106.0    12720   Pave   NaN      Reg
1699          20       RL          NaN    10750   Pave   NaN      IR1
1700          60       RL         79.0     9085   Pave   NaN      Reg
1701          60       RL          NaN    11692   Pave   NaN      IR1
1702          20       RL         86.0    11194   Pave   NaN      IR1
1703          20       RL         78.0    10206   Pave   NaN      Reg
1704          20       RL         85.0    10130   Pave   NaN      Reg
1705          20       RL         76.0     9139   Pave   NaN      IR1
1706          20       RL         85.0    11128   Pave   NaN      Reg
1707          20       FV         90.0     7993   Pave   NaN      IR1
1708          20       FV         72.0     8640   Pave   NaN      Reg
1709          20       FV        112.0    12606   Pave   NaN      IR1
1710          20       FV         75.0     7500   Pave   NaN      Reg
1711          60       FV         84.0    10603   Pave   NaN      Reg
1712          20       FV         65.0     8125   Pave   NaN      Reg
1713          20       FV         85.0    10625   Pave   NaN      Reg
1714          20       FV         68.0     8736   Pave   NaN      IR1
1715          60       FV         65.0     8127   Pave   NaN      IR1
1716          20       RL         80.0     9605   Pave   NaN      Reg
1717          20       RL         63.0     7500   Pave   NaN      Reg
1718          20       RL         63.0     7500   Pave   NaN      Reg
1719          60       RL         96.0    10628   Pave   NaN      IR1
1720          20       RL         76.0    10141   Pave   NaN      IR1
1721          20       RL         63.0    13072   Pave   NaN      Reg
1722          20       RL         63.0    13072   Pave   NaN      Reg
1723          20       RL         60.0    12450   Pave   NaN      Reg
1724          20       RL         61.0     7328   Pave   NaN      Reg
1725          60       RL         43.0    11492   Pave   NaN      IR1
1726          60       RL         70.0     7703   Pave   NaN      Reg
1727         120       RL         50.0     7175   Pave   NaN      Reg
1728          60       RL         70.0     9109   Pave   NaN      Reg
1729          60       RL          NaN    10274   Pave   NaN      IR1
1730          90       RL         75.0     8250   Pave   NaN      Reg
1731          20       RL         63.0     9750   Pave   NaN      IR1
1732          20       RL          NaN     8499   Pave   NaN      IR1
1733          20       RL          NaN     9079   Pave   NaN      IR1
1734          20       RL          NaN     9316   Pave   NaN      IR1
1735          20       RL          NaN     7791   Pave   NaN      IR1
1736          20       RL         65.0     7150   Pave   NaN      Reg
1737          20       RL          NaN    15676   Pave   NaN      IR1
1738          60       RL          NaN    11949   Pave   NaN      Reg
1739         160       FV         32.0     2880   Pave  Pave      Reg
1740         120       FV          NaN     3830   Pave  Pave      IR1
1741         120       FV          NaN     4217   Pave  Pave      IR1
1742         160       FV         34.0     2998   Pave   NaN      Reg
1743         160       FV         35.0     3768   Pave   NaN      Reg
1744          20       RL          NaN    14694   Pave   NaN      IR1

In [7]:
categorical_cols = train_df.select_dtypes(include=['object']).columns.tolist()
train_df_encoded = pd.get_dummies(train_df, columns=categorical_cols)
test_df_encoded = pd.get_dummies(test_df, columns=categorical_cols)

In [8]:
common_cols = list(set(train_df_encoded.columns) & set(test_df_encoded.columns))
train_filtered = train_df_encoded[common_cols]
test_filtered = test_df_encoded[common_cols]

In [9]:
X = train_filtered
y = train_df['SalePrice']

In [10]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, learning_rate=0.1, random_state=42)
model.fit(X_train, y_train)
predictions = model.predict(X_val)
mae = mean_absolute_error(y_val, predictions)
print(mae)

16509.37607020548

In [12]:
y = model.predict(test_filtered)

In [13]:
test_df.set_index('Id',inplace = True)
test_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [14]:
submission_df = pd.DataFrame({
    'Id': test_df.index,
    'SalePrice': y
})

In [15]:
submission_df.to_csv('submission.csv', index=False)

print("✅ submission.csv file created successfully!")

✅ submission.csv file created successfully!